### ISSUE TITLE
動画投稿機能の追加

### ISSUE THREAD

**Issue by daisuke8000** [daisuke8000/VideoRooms#19]
アップローダーの作成
YouTube Player APIを使用する

**Comment by kazup1125** [comment]
動画投稿にURLを貼り付けられるようにする

**Comment by kazup1125** [comment]
videos にカラムを追加する
`url:string`

**Comment by kazup1125** [comment]
shared/videos_new に入力フォームを追加する。

**Comment by kazup1125** [comment]
- [ ] videos にカラムを追加する

- [ ] shared/videos_new に入力フォームを追加する

- [ ] ストロングパラメータ等コントローラーの修正
