### ISSUE TITLE
マイグレーションファイル　モデルファイルの作成

### ISSUE THREAD

**Issue by kazup1125** [daisuke8000/VideoRooms#4]
・videos
・rooms
・users

**Comment by kazup1125** [comment]
Viewを作る手順
1. マイグレーションファイルを作る
2. モデルの関連付けを記述する
3. コントローラーを作成する
4. ルーティングを設定する
5. ビューファイルを作成する
6. アクセスして確かめてみる
7. 導線完成！

**Comment by daisuke8000** [comment]
### 変更内容
- リポジトリ名の変更
(old) `daisuke8000/portfolio1`
(new) `daisuke8000/videos-rooms-users`

ご確認宜しくお願いします。

**Comment by kazup1125** [comment]
あ、リポジトリ名はアプリの名前とかでいいと思いますよ！
`VIideoRooms` とか！👍🏻

**Comment by daisuke8000** [comment]
おつかれさまです！
あ、失礼しました🙀
もう一度修正しておきます！

2020年5月5日(火) 17:48 kazup1125 <notifications@github.com>:

**Comment by kazup1125** [comment]
ブランチ名はこんな感じならわかりやすいと思います。
今回でいうと、
issueのタイトル：マイグレーションファイル　モデルファイルの作成 #4
ブランチ名：`issues/4`

**Comment by daisuke8000** [comment]
### 変更内容（再変更）
- リポジトリ名の変更
(old) `daisuke8000/videos-rooms-users`
(new) `daisuke8000/VideoRooms`

ブランチ名の付け方も参考になります！
ありがとうございます！
