### ISSUE TITLE
モデルのアソシエーション（関連付け）

### ISSUE THREAD

**Issue by kazup1125** [daisuke8000/VideoRooms#7]
User
has_many rooms

Room
belongs_to user
has_many videos

Video
has_many rooms

**Comment by kazup1125** [comment]
Qiita
https://qiita.com/kazukimatsumoto/items/14bdff681ec5ddac26d1

**Comment by daisuke8000** [comment]
### 実装予定
- テーブルカラム修正
- Qiita記事参考にモデル関連付け実装

**Comment by daisuke8000** [comment]
追加記事
https://qiita.com/ryouzi/items/2682e7e8a86fd2b1ae47
